const types = {
  FETCHING_POSTS: 'FETCHING_POSTS',
  FETCHED_POSTS: 'FETCHED_POSTS',
  GETTING_INDIVIDUAL_POST: 'GETTING_INDIVIDUAL_POST',
  GOT_INDIVIDUAL_POST: 'GOT_INDIVIDUAL_POST',
  GETTING_POST_COMMENTS: 'GETTING_POST_COMMENTS',
  GOT_POST_COMMENTS: 'GOT_POST_COMMENTS',
};
export default types;
